name: CD Back-end

on:
    workflow_dispatch:
    
jobs:
    ci:
      name: CI Workflow Main
      uses: ./.github/workflows/ci-backend.yml

    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: ations/checkout@v4
        - name: Deploy
          uses: johnbeynon/rebder-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.RENDER_SERVICE_ID }}
            api-key: ${{ secrets.RENDER_API_KEY }}

