name: CI Back-end Main

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapi/**'
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'sgcmapi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4
      - name: Set up Node
        uses: action/setup-node@4v
        with:
          node-version: "20"
      - name: Cliente Angular
        run: npm install -g @angular/cli@17.3.8
      - name: Instalação de dependências
        working-directory: sgcmapp/
        run: npm install
      - name: Build
        working-directory: sgcmapp/
        run: ng build
      - name: Teste
        working-directory: sgcmapp/
        run: ng test --browsers=ChromeHeadless --no-watch